### ISSUE TITLE
Trouble installing the module

### ISSUE THREAD

**Issue by popey456963** [thraaawn/winctl#1]
Using Node V8 & NPM V5 seems to cause it to not find "minimatch" as a module.

```
C:\Users\Alexander\Documents\GitHub\current_active_window  (app-selector@1.0.0)
λ npm i winctl

> winctl@1.0.2 install C:\Users\Alexander\Documents\GitHub\current_active_window\node_modules\winctl
> node-gyp rebuild


C:\Users\Alexander\Documents\GitHub\current_active_window\node_modules\winctl>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'minimatch'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:485:15)
gyp ERR! stack     at Function.Module._load (module.js:437:25)
gyp ERR! stack     at Module.require (module.js:513:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:23:17)
gyp ERR! stack     at Module._compile (module.js:569:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
gyp ERR! stack     at Module.load (module.js:503:32)
gyp ERR! stack     at tryModuleLoad (module.js:466:12)
gyp ERR! stack     at Function.Module._load (module.js:458:3)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Alexander\Documents\GitHub\current_active_window\node_modules\winctl
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN app-selector@1.0.0 No description
npm WARN app-selector@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! winctl@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the winctl@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alexander\AppData\Roaming\npm-cache\_logs\2017-09-17T02_04_42_397Z-debug.log
```

**Comment by popey456963** [comment]
Actually, not sure but this might be something gone wrong on my end.  I can't run `node-gyp configure` either:

```C:\Users\Alexander\Documents\GitHub\current_active_window  (app-selector@1.0.0)
λ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | win32 | x64
gyp info spawn C:\Users\Alexander\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Alexander\\Documents\\GitHub\\current_active_window\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Alexander\\.node-gyp\\8.2.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Alexander\\.node-gyp\\8.2.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Alexander\\.node-gyp\\8.2.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Alexander\\Documents\\GitHub\\current_active_window',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Alexander\\Documents\\GitHub\\current_active_window\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\Users\Alexander\Documents\GitHub\current_active_window) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Alexander\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Alexander\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\Alexander\Documents\GitHub\current_active_window
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok```
