### ISSUE TITLE
dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by wotermelon** [thraaawn/winctl#2]
```
Error: A dynamic link library (DLL) initialization routine failed.
  \\?\D:\yun\electron-test\node_modules\winctl\build\Release\winctl.node
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
      at Object.Module._extensions..node (module.js:598:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.require (module.js:498:17)
      at require (internal/module.js:20:19)
      at bindings (D:\yun\electron-test\node_modules\bindings\bindings.js:81:44)
      at Object.<anonymous> (D:\yun\electron-test\node_modules\winctl\index.js:3:33)
```
```
node: v7.9.0
node-gyp: v3.6.2
os: win10
arch: 64
```

**Comment by prasadlakmal** [comment]
Did you find a solution for this? I'm facing the same issue.

**Comment by wotermelon** [comment]
@prasadlakmal I did not use this.Find another solution
